### ISSUE TITLE
针对Models进行加工 

### ISSUE THREAD

**Issue by cjwn** [900wan/waihui-django#6]
希望给office页面sku列表增加一列显示这节课是否处于可以点Ready的状态，目前遇到问题是如何在不修改models的基础上针对models的属性进行扩充。今天发现一个setattr()的功能，确实可以方便地临时给models增加属性，但是我写的views应该有问题，并没有对skus们进行加工，结果只输出了一个sku
- [ ] 尝试加工后输出完整的skus

**Comment by coolgene** [comment]
setattr() 函数如果可以给models增加属性的话，听起来不错啊！

2016-03-30 1:19 GMT+08:00 cjwn notifications@github.com:

**Comment by coolgene** [comment]
https://github.com/900wan/waihui-django/commit/121c7159c47df45485b733e567a989899c9a52b3 <--这个 commit。
- 把 act_is_course_ready() 改名叫 act_expand_skus()，这样就是用来扩展 skus 用。
- 根据距离上课时间的远近，区分出了 start_later、start_soon、should_in_progress、past
  四种时间状态。不过值得留意的是，这只是仅仅根据距离上课时间推算的，不代表老师或学生真的来了，所以这只是用来给程序判断使用的。比如当处于
  start_soon 的时候，才给用户展示上课链接等等判断。
- 相应的，对 office.html 模版也做了一点修改。

**Comment by cjwn** [comment]
a298e676658e95586f3b8739bb823440ac7f83a9 <--这个commit。
我也学习一下
